// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingBotApp.Data;

#nullable disable

namespace TradingBotApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220226011918_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TradingBotApp.Models.RamvQualifierTool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("MacdMaxDeviation")
                        .HasColumnType("float");

                    b.Property<int>("MaxRecurrentCandleStickPeriod")
                        .HasColumnType("int");

                    b.Property<int>("MinRecurrentCandleStickPeriod")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("ToolTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RamvQualifiers");
                });

            modelBuilder.Entity("TradingBotApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RamvQualifierToolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RamvQualifierToolId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TradingBotApp.Models.User", b =>
                {
                    b.HasOne("TradingBotApp.Models.RamvQualifierTool", "RamvQualifierTool")
                        .WithMany()
                        .HasForeignKey("RamvQualifierToolId");

                    b.Navigation("RamvQualifierTool");
                });
#pragma warning restore 612, 618
        }
    }
}
